#!/usr/bin/env python3
"""Generate src/uktextnorm/generated/uktextnorm_lexicons.hpp from data/lexicons/*.tsv.

Usage: gen_lexicon.py <lexicon_dir> <output_header>

The TSV files are UTF-8, tab-separated, with a header row; lines starting
with '#' are comments. Row order is preserved. Malformed rows, wrong column
counts, and duplicate keys fail the build.
"""
import sys
import unicodedata
from pathlib import Path

TABLES = {
    # file: (array name, struct name, columns, (bool column names))
    "units.tsv": ("kUnits", "UnitEntry",
                  ["key", "one", "few", "many", "gender"], set()),
    "counted_nouns.tsv": ("kCountedNouns", "CountedNounEntry",
                          ["key", "one", "few", "many", "gender"], set()),
    "acronyms.tsv": ("kAcronyms", "AcronymEntry",
                     ["acronym", "expansion"], set()),
    "abbreviations.tsv": ("kAbbreviations", "AbbreviationEntry",
                          ["key", "expansion"], set()),
    "brands.tsv": ("kBrands", "BrandEntry",
                   ["latin", "cyrillic"], set()),
    "english_words.tsv": ("kEnglishWords", "EnglishWordEntry",
                          ["latin", "cyrillic"], set()),
    "finance_units.tsv": ("kFinanceUnits", "FinanceUnitEntry",
                          ["code", "one", "few", "many", "feminine"], {"feminine"}),
    "currencies.tsv": ("kCurrencies", "CurrencyEntry",
                       ["code", "symbol", "word_re", "main_one", "main_few", "main_many",
                        "main_fem", "sub_one", "sub_few", "sub_many", "sub_fem",
                        "trailing_symbol"],
                       {"main_fem", "sub_fem", "trailing_symbol"}),
}

# Duplicate keys are checked on the first column of each table.
GENDERS = {"m", "f", "n"}


def fail(msg: str) -> None:
    print(f"gen_lexicon.py: error: {msg}", file=sys.stderr)
    sys.exit(1)


def cpp_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def read_table(path: Path, columns, bools):
    rows = []
    seen = set()
    lines = path.read_text(encoding="utf-8").splitlines()
    data_lines = [(i + 1, ln) for i, ln in enumerate(lines) if ln and not ln.startswith("#")]
    if not data_lines:
        fail(f"{path.name}: empty table")
    header_no, header = data_lines[0]
    if header.split("\t") != columns:
        fail(f"{path.name}:{header_no}: header must be {chr(9).join(columns)!r}")
    for lineno, line in data_lines[1:]:
        fields = line.split("\t")
        if len(fields) != len(columns):
            fail(f"{path.name}:{lineno}: expected {len(columns)} columns, got {len(fields)}")
        row = dict(zip(columns, fields))
        key = fields[0]
        if key in seen:
            fail(f"{path.name}:{lineno}: duplicate key {key!r}")
        seen.add(key)
        for col, value in row.items():
            if unicodedata.normalize("NFC", value) != value:
                fail(f"{path.name}:{lineno}: column {col!r} is not NFC-normalized")
            if col in bools:
                if value not in ("0", "1"):
                    fail(f"{path.name}:{lineno}: column {col!r} must be 0 or 1")
            elif col == "gender":
                if value not in GENDERS:
                    fail(f"{path.name}:{lineno}: gender must be one of {sorted(GENDERS)}")
            elif not value and col not in ("word_re", "symbol"):
                fail(f"{path.name}:{lineno}: column {col!r} is empty")
        rows.append(row)
    return rows


def emit_field(col: str, value: str, bools) -> str:
    if col in bools:
        return "true" if value == "1" else "false"
    if col == "gender":
        return f"'{value}'"
    return f'"{cpp_escape(value)}"'


def main() -> None:
    if len(sys.argv) != 3:
        fail("usage: gen_lexicon.py <lexicon_dir> <output_header>")
    lexicon_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    parts = [
        "// Generated by cmake/gen_lexicon.py from data/lexicons/*.tsv. Do not edit.\n"
        "#pragma once\n\n"
        "#include <array>\n"
        "#include <string_view>\n\n"
        "namespace uktextnorm::lexicon {\n"
    ]
    for filename, (array, struct, columns, bools) in TABLES.items():
        rows = read_table(lexicon_dir / filename, columns, bools)
        fields = []
        for col in columns:
            if col in bools:
                fields.append(f"    bool {col} = false;")
            elif col == "gender":
                fields.append(f"    char {col} = 'm';")
            else:
                fields.append(f"    std::string_view {col};")
        parts.append(f"\nstruct {struct} {{\n" + "\n".join(fields) + "\n};\n")
        parts.append(f"\ninline constexpr std::array<{struct}, {len(rows)}> {array} = {{{{\n")
        for row in rows:
            values = ", ".join(emit_field(col, row[col], bools) for col in columns)
            parts.append(f"    {{{values}}},\n")
        parts.append("}};\n")
    parts.append("\n} // namespace uktextnorm::lexicon\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = "".join(parts)
    if not out_path.exists() or out_path.read_text(encoding="utf-8") != text:
        out_path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
